version: '3.4'

services:
  postgres:
    container_name: graphql-prisma
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gprisma
      - POSTGRES_PASSWORD=prisma


volumes:
  postgres_data: